spring:
  datasource:
    password: password
    username: yusuke
    url: jdbc:mysql://localhost:3306/isucon11?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
    initialize: false