spring:
  datasource:
    password: ${ISUCON11Q_PASSWORD}
    username: ${ISUCON11Q_USERNAME}
    url: jdbc:mysql://localhost:3306/isucon11?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.jdbc.Driver
    sql-script-encoding: UTF-8
    initialize: false