server:
  port: 3000
spring:
  datasource:
    username: ${MYSQL_USER}
    password: ${MYSQL_PASS}
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DBNAME}?useUnicode=true&characterEncoding=utf8
    driver-class-name: com.mysql.cj.jdbc.Driver
    sql-script-encoding: UTF-8
    initialize: false
